### ISSUE TITLE
测试图像不是矩形，或者太小怎么处理呀

### ISSUE THREAD

**Issue by Yansusu12** [edbca/DARSR#2]
作者您好，我在测试模型的时候发现，Set5上的图像过程中存在下采样的图像太小，导致最后特征小于卷积核，这块怎么处理呀，或者作者您是如何测试的呢

**Comment by edbca** [comment]
这种方法的缺点就是图像尺寸太小的话，性能不好但是也能运行 在option.py中改小训练图像的crop_size。crop_size肯定要小于你的输入图像的大小，不然不能运行，但是要小到多少，就要看实际情况了。


测试图像不是矩形？这个我不太懂是什么意思，图像尺寸的尺寸是多少？

**Comment by Yansusu12** [comment]
比如Set5里woman.png,下采样后变成57x86，这跑的时候就会出错，应该是data.py里的数据增强带来的问题
<img width="509" alt="微信图片_20231127131906" src="https://github.com/edbca/DARSR/assets/142860970/d5a46a80-01f9-42d4-bbbe-9b64a0feaddf">

**Comment by Yansusu12** [comment]
![image](https://github.com/edbca/DARSR/assets/142860970/4d6ac4f4-0c95-451e-9ffc-13c3b28b4092)
实际测试时发现输入分辨率为57x86时，crop_size调整为40，32都会出错 请问下这个怎么处理呀，麻烦了 @edbca

**Comment by Yansusu12** [comment]
找到问题了，抱歉，打扰您了
