### ISSUE TITLE
测试问题

### ISSUE THREAD

**Issue by Yansusu12** [edbca/DARSR#4]
作者您好，请问是每一张都必须要单独训练一个模型吗，相同退化的图像可以共用一个模型吗

**Comment by edbca** [comment]
是每张图像训练一次 相同退化的图像要共用一个模型 需要更改代码 让代码保存模型
但是不建议那么做 因为这种自监督的方法对输入图像的纹理很敏感 要是只用一张图训练 去推理其他图的话 效果肯定大打折扣




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "edbca/DARSR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月4日(星期一) 中午1:57
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[edbca/DARSR] 测试问题 (Issue #4)





 
作者您好，请问是每一张都必须要单独训练一个模型吗，相同退化的图像可以共用一个模型吗
