### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by Chantec** [edbca/DARSR#6]
报错信息：RuntimeError: Padding size should be less than the corresponding input dimension, but got: padding (2, 2) at dimension 3 of input [16, 3, 2, 2]
图片是128*128尺寸的
请问是什么原因呢？

**Comment by edbca** [comment]
您好 输入图片的尺寸太小 你可以在option.py中降低--input_crop_size的大小 可以尝试96、64试试 （默认是128，输入图片的尺寸需要大于这个数值，不然无法运行）&nbsp;



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Liang ***@***.***&gt;; 
发送时间: 2024年6月28日(星期五) 下午5:02
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [edbca/DARSR] 运行报错 (Issue #6)














 
报错信息：RuntimeError: Padding size should be less than the corresponding input dimension, but got: padding (2, 2) at dimension 3 of input [16, 3, 2, 2]
 图片是128*128尺寸的
 请问是什么原因呢？

**Comment by Chantec** [comment]
> 您好 输入图片的尺寸太小 你可以在option.py中降低--input_crop_size的大小 可以尝试96、64试试 （默认是128，输入图片的尺寸需要大于这个数值，不然无法运行）&nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Liang ***@***.***&gt;; 发送时间: 2024年6月28日(星期五) 下午5:02 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [edbca/DARSR] 运行报错 (Issue #6) 报错信息：RuntimeError: Padding size should be less than the corresponding input dimension, but got: padding (2, 2) at dimension 3 of input [16, 3, 2, 2] 图片是128*128尺寸的 请问是什么原因呢？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

谢谢您的回复！已成功解决！
